CREATE TABLE User_Master(userId VARCHAR2(6) PRIMARY KEY,userName VARCHAR2(15),userPassword VARCHAR2(50),
userType VARCHAR2(10));==

CREATE TABLE DepartmentsDetails(Dept_ID int PRIMARY KEY, Dept_Name VARCHAR2(50) );==


CREATE TABLE Employees(Empno Number(6), Ename Varchar2(25), job Varchar2(50), mgr number(4), hiredate date, Dept_ID number,
FOREIGN KEY (Dept_ID) REFERENCES DepartmentsDetails(Dept_Id)); ==

CREATE TABLE	Asset( AssetId Number PRIMARY KEY, AssetName Varchar2(25), AssetDes Varchar2(25), Quantity Number, Status Varchar2(15));==

CREATE TABLE Asset_Allocation(AllocationId Number PRIMARY KEY, AssetId Number, Empno Number, Allocation_date Date, Release_date Date,
FOREIGN KEY (AssetId) REFERENCES Asset(AssetId)); ==
desc Asset_Allocation;

INSERT INTO User_Master VALUES ('CG101','SNEHAL BAGADE','CORP','USER');

INSERT INTO User_Master VALUES ('CG102','SHWETA TRIPATHI','CORP','ADMIN');

INSERT INTO User_Master VALUES ('CG103','VINAYAK KEDIA','CAPGEMINI','USER');

INSERT INTO User_Master VALUES ('CG104','SAYANTANI','CAPGEMINI','USER');

INSERT INTO User_Master VALUES ('CG105','ROHIT','CAPGEMINI','USER');

INSERT INTO User_Master VALUES ('CG106','PRANJALI','CORP','USER');

INSERT INTO User_Master VALUES ('CG107','RAHUL','CORP','USER');

select * from User_Master;


[?10/?14/?2017 10:45 AM] Tripathi, Shweta: 
No Title


INSERT INTO DepartmentsDetails VALUES (111,'DEVELPOMENT');
INSERT INTO DepartmentsDetails VALUES (112,'TESTING');
INSERT INTO DepartmentsDetails VALUES (113,'SUPPORT');
INSERT INTO DepartmentsDetails VALUES (114,'MAINTAINANCE');
INSERT INTO DepartmentsDetails VALUES (115,'FINANCE');
INSERT INTO DepartmentsDetails VALUES (116,'BUSINESS_UNIT');
SELECT * FROM DepartmentsDetails;


INSERT INTO  Asset VALUES(001,'LAPTOP','HARDWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(002,'PRINTER','HARDWARE',6,'DEALLOCATED');

INSERT INTO  Asset VALUES(003,'MATLAB','SOFTWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(004,'PROJECTOR','HARDWARE',4,'DEALLOCATED');

INSERT INTO  Asset VALUES(005,'ORACLE','SOFTWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(006,'ANTIVIRUS','SOFTWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(007,'HARD_DISK','HARDWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(008,'MOBILE_PHONE','HARDWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(009,'VMWARE','SOFTWARE',10,'DEALLOCATED');

INSERT INTO  Asset VALUES(010,'PROPEL','STUDY_MATERIAL',10,'DEALLOCATED');
SELECT * FROM ASSET; 

commit

INSERT INTO Employee VALUES (1001,'SNEHAL BAGADE','ANALYST','1005',TO_DATE('02/06/2017','dd/mm/yyyy'),111);



INSERT INTO Employee VALUES (1002,'SHWETA TRIPATHI','SENIOR ANALYST','1005',TO_DATE('12/01/2017','dd/mm/yyyy'),111);


INSERT INTO Employee VALUES (1003,'VINAYAK KEDIA','DESIGNER','1006',TO_DATE('02/02/2017','dd/mm/yyyy'),113);


INSERT INTO Employee VALUES (1004,'SAYANTANI','ASSEMBLER','1006',TO_DATE('15/02/2017','dd/mm/yyyy'),114);

INSERT INTO Employee VALUES (1005,'ROHIT','MANAGER',null,TO_DATE('03/08/2017','dd/mm/yyyy'),111);

INSERT INTO Employee VALUES (1006,'PRANJALI','SENIOR_MANAGER',NULL,TO_DATE('01/05/2016','dd/mm/yyyy'),116);


INSERT INTO Employee VALUES (1007,'RAHUL','TESTER',1012,TO_DATE('03/01/2015','dd/mm/yyyy'),112);



INSERT INTO Employee VALUES (1008,'GOVIND','ADVISOR',1006,TO_DATE('03/08/2017','dd/mm/yyyy'),115);


INSERT INTO Employee VALUES (1009,'SHARVARI','TECHNICIAN',1010,TO_DATE('03/01/2017','dd/mm/yyyy'),113);


INSERT INTO Employee VALUES (1010,'PALAK','CO-ORDINATOR',1006,TO_DATE('09/08/2014','dd/mm/yyyy'),116);

INSERT INTO Employee VALUES (1011,'SUMEDHA','EXECUTIVE',1010,TO_DATE('16/10/2013','dd/mm/yyyy'),115);


INSERT INTO Employee VALUES (1012,'ROSY','SENIOR_TESTER',null,TO_DATE('03/05/2012','dd/mm/yyyy'),112); 


